import { StyleSheet } from 'react-native';
export const S = StyleSheet.create({
    flex: { flex: 1 },
    flex2: { flex: 2 },
    flex3: { flex: 3 },
    flex4: { flex: 4 },
    flex5: { flex: 5 },
    flexGrow1: { flexGrow: 1 },
    flexShrink1: { flexShrink: 1 },
    flexWrap: { flexWrap: 'wrap' },
    fill: { width: '100%', height: '100%' },
    row: { flexDirection: 'row' },
    rowReverse: { flexDirection: 'row-reverse' },
    wrap: { flexWrap: 'wrap' },
    start: { justifyContent: 'flex-start' },
    end: { justifyContent: 'flex-end' },
    between: { justifyContent: 'space-between' },
    around: { justifyContent: 'space-around' },
    evenly: { justifyContent: 'space-evenly' },
    flexEnd: { alignItems: 'flex-end' },
    flexStart: { alignItems: 'flex-start' },
    center: { alignItems: 'center' },
    selfCenter: { alignSelf: 'center' },
    justify: { justifyContent: 'center' },
    pad: { padding: 4 },
    pad1: { padding: 8 },
    pad2: { padding: 16 },
    mReset: { marginLeft: 0, marginRight: 0, marginTop: 0, marginBottom: 0 },
    m: { margin: 4 },
    m1: { margin: 8 },
    m2: { margin: 16 },
    pReset: {
        paddingLeft: 0,
        paddingRight: 0,
        paddingTop: 0,
        paddingBottom: 0,
    },
    pt0: { paddingTop: 4 },
    pt1: { paddingTop: 8 },
    pt2: { paddingTop: 16 },
    pr0: { paddingRight: 4 },
    pr1: { paddingRight: 8 },
    pr2: { paddingRight: 16 },
    pb0: { paddingBottom: 4 },
    pb1: { paddingBottom: 8 },
    pb2: { paddingBottom: 16 },
    pl0: { paddingLeft: 4 },
    pl1: { paddingLeft: 8 },
    pl2: { paddingLeft: 16 },
    ph0: { paddingHorizontal: 4 },
    ph1: { paddingHorizontal: 8 },
    ph2: { paddingHorizontal: 16 },
    pv0: { paddingVertical: 4 },
    pv1: { paddingVertical: 8 },
    pv2: { paddingVertical: 16 },
    mh0: { marginHorizontal: 4 },
    mh1: { marginHorizontal: 8 },
    mh2: { marginHorizontal: 16 },
    mv0: { marginVertical: 4 },
    mv1: { marginVertical: 8 },
    mv2: { marginVertical: 16 },
    mr0: { marginRight: 4 },
    mr1: { marginRight: 8 },
    mr2: { marginRight: 16 },
    ml0: { marginLeft: 4 },
    ml1: { marginLeft: 8 },
    ml2: { marginLeft: 16 },
    mb0: { marginBottom: 4 },
    mb1: { marginBottom: 8 },
    mb2: { marginBottom: 16 },
    mb3: { marginBottom: 32 },
    mt0: { marginTop: 4 },
    mt1: { marginTop: 8 },
    mt2: { marginTop: 16 },
    wFull: { width: '100%' },
    w75: { width: '75%' },
    w25: { width: '25%' },
    w50: { width: '50%' },
    hFull: { height: '100%' },
    overflowHidden: { overflow: 'hidden' },
    rounded50: {
        overflow: 'hidden',
        borderRadius: 50,
    },
    rowAround: {
        flexDirection: 'row',
        justifyContent: 'space-around',
    },
    divider: {
        height: StyleSheet.hairlineWidth,
        backgroundColor: 'transparent',
        marginVertical: 12,
        width: '100%',
    },
    textCenter: { textAlign: 'center' },
    textRight: { textAlign: 'right' },
    textLeft: { textAlign: 'left' },
    textJustify: { textAlign: 'justify' },
    textVCenter: { textAlignVertical: 'center' },
    textVTop: { textAlignVertical: 'top' },
    textVBottom: { textAlignVertical: 'bottom' },
    darkOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        height: '100%',
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.6)',
    },
    radius: { borderRadius: 6 },
    radius1: { borderRadius: 12 },
    radius2: { borderRadius: 20 },
});
